// Dependency-free DOM simulation: tests handlers/math, NOT browser rendering.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class El {
 constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.dataset={};this.style={};this.value='';this.checked=false;this.classList={toggle(){}};}
 append(...v){this.children.push(...v);} replaceChildren(...v){this.children=[...v];}
 setAttribute(k,v){this.attrs[k]=String(v);} getAttribute(k){return this.attrs[k];}
 createSVGPoint(){return {x:0,y:0,matrixTransform(){return {x:this.x,y:this.y};}};}
 getScreenCTM(){return {inverse(){return {};}};}
}
const html=fs.readFileSync('app/templates/portfolio.html','utf8'), ids={};
for(const m of html.matchAll(/id="([^"]+)"/g))ids[m[1]]=new El('div');
ids['show-sma'].checked=true;
ids['chart-kind'].value='candles';
const bars=Array.from({length:100},(_,i)=>({day:new Date(Date.UTC(2026,0,1+i)).toISOString().slice(0,10),close:100+i,open:99+i,high:105+i,low:97+i}));
bars[0]={day:bars[0].day,close:100}; // Legacy close-only data must not get invented candles.
ids['portfolio-data'].textContent=JSON.stringify({mock:true,generated_at:new Date().toISOString(),connections:[],last_run:null,news:[],portfolio_review:null,stocks:[{symbol:'NVDA',name:'Nvidia',price:200,as_of:new Date().toISOString(),bars,signals:[],stale:false,indicators:{daily_change_pct:1,sma20:190,sma50:175,rsi14:60}}]});
const ranges=[20,50,100].map(n=>{const e=new El('button');e.dataset.range=String(n);return e;});
const document={getElementById:id=>ids[id],createElement:tag=>new El(tag),createElementNS:(ns,tag)=>new El(tag),createTextNode:text=>text,querySelectorAll:()=>ranges};
const docEvents={};document.addEventListener=(name,fn)=>{const prior=docEvents[name];docEvents[name]=e=>{prior?.(e);fn(e);};};
const script=html.split('<script>')[1].split('</script>')[0]+'\n'+fs.readFileSync('app/templates/portfolio-dashboard.js','utf8');
const runtime={document,Intl,Date,Map,Number,Math,JSON,String};
vm.runInNewContext(script,runtime);
ids['bar-size'].value='day';ids['bar-size'].onchange();ids['zoom-in'].onclick();
const chart=ids.chart;
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,50);
assert.equal(chart.children.filter(e=>e.attrs?.['data-wick']).length,50);
assert.equal(typeof chart.onpointermove,'function');
chart.onpointermove({clientX:5,clientY:100});
assert.match(ids['hover-tip'].textContent,/150\.00/);
assert.match(ids['hover-tip'].textContent,/สูงสุด \$155\.00/);
assert.match(ids['hover-tip'].textContent,/ต่ำสุด \$147\.00/);
chart.onpointerdown({clientX:5,clientY:100});
chart.onpointermove({clientX:650,clientY:100});
assert.match(ids['hover-tip'].textContent,/150\.00/,'pinned point stays put');
chart.onkeydown({key:'ArrowRight',preventDefault(){}});
assert.match(ids['hover-tip'].textContent,/151\.00/);
chart.onkeydown({key:'Escape',preventDefault(){}});
assert.match(ids['hover-tip'].textContent,/199\.00/);
ids['point-slider'].oninput({target:{value:'0'}});
assert.match(ids['hover-tip'].textContent,/150\.00/);
ids['zoom-in'].onclick();assert.match(ids['chart-dates'].textContent,/25 แท่ง/);
ids['all-bars'].onclick();assert.match(ids['chart-dates'].textContent,/100 แท่ง/);
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,99);
assert.equal(chart.children.filter(e=>e.attrs?.['data-close-only']).length,1);
ids['chart-kind'].value='line';ids['chart-kind'].onchange();
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,0);
ids['chart-kind'].value='candles';ids['chart-kind'].onchange();
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,99);
ids['date-from'].value=bars[0].day;ids['date-to'].value=bars[9].day;ids['date-from'].onchange();
assert.match(ids['chart-dates'].textContent,/10 แท่ง/);
ids['date-from'].value=bars[9].day;ids['date-from'].onchange();
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,1);
chart.onpointermove({clientX:300,clientY:100});
assert.match(ids['hover-tip'].textContent,/109\.00/);
ids['date-from'].value='2099-01-01';ids['date-from'].onchange();
assert.equal(chart.onpointermove,null);assert.equal(ids['point-slider'].disabled,true);
ids['chart-range'].value='1m';ids['chart-range'].onchange();assert.ok(chart.children.length>0);
ids['show-sma'].checked=false;ids['show-sma'].onchange();
assert.equal(typeof chart.onpointermove,'function');
const extended=Array.from({length:300},(_,i)=>({day:new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,10),close:100+i,open:99+i,high:105+i,low:97+i}));
assert.equal(runtime.averages(extended,200)[198],null);
assert.equal(runtime.averages(extended,200)[199],199.5);
assert.equal(runtime.averages(extended,200).at(-1),299.5);
const monthly=runtime.groupBars(extended,'month');
assert.equal(monthly[0].open,99);assert.equal(monthly[0].close,130);assert.equal(monthly[0].high,135);assert.equal(monthly[0].low,97);
ids['bar-size'].value='month';ids['bar-size'].onchange();assert.match(ids['series-caption'].textContent,/1 เดือน/);
// Use a second isolated page for five-minute bars and display controls.
const demo=JSON.parse(ids['portfolio-data'].textContent);
demo.portfolio={as_of:'2026-09-23',total_usd:100,dca:{monthly_total:1800,per_stock:200,day:28},allocations:{sectors:[{label:'Tech',value_usd:100,weight_pct:100}],exposures:[{label:'AI',value_usd:100,weight_pct:100}]},holdings:[{symbol:'META',quantity:.5,value_usd:100,weight_pct:100,gain_pct:10,estimated_cost_usd:90.91,thesis:'User belief'}]};
demo.news=[{symbol:'META',published_at:'2026-09-22T00:00:00Z',title:'Financial results',reason:'ผลประกอบการ',source_name:'Official',source_id:'abc'}];
demo.portfolio_review={period:'2026-W39',created_at:'2026-09-23T00:00:00Z',ai_used:false,message:'Saved review'};
demo.stocks[0].intraday=Array.from({length:78},(_,i)=>({day:'2026-09-22',at:new Date(Date.UTC(2026,8,22,13,30+i*5)).toISOString(),open:100+i,high:102+i,low:99+i,close:101+i,session_end:'2026-09-22T20:00:00Z'}));
demo.stocks[0].intraday_previous={'2026-09-22':100};
ids['portfolio-data'].textContent=JSON.stringify(demo);
const second={document,Intl,Date,Map,Number,Math,JSON,String};vm.runInNewContext(script,second);
assert.equal(ids['holdings-panel'].hidden,false);
assert.equal(ids['allocation-panel'].hidden,false);
assert.equal(ids['sector-donut'].children.filter(e=>e.attrs?.['data-allocation']).length,1);
assert.equal(ids['sector-legend'].children.length,1);
assert.equal(ids['exposure-bars'].children.length,2);
assert.match(ids['portfolio-review'].textContent,/Saved review/);
assert.equal(ids['news-list'].children.length,1);
assert.match(ids['holdings-summary'].textContent,/100.00/);
assert.equal(ids['holdings-rows'].children.length,1);
assert.equal(ids['holdings-rows'].children[0].children[1].textContent,'0.5');
assert.match(ids['dca-plan'].textContent,/1,800.00/);
ids['chart-range'].value='1d';ids['chart-range'].onchange();
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,78);
assert.equal(chart.children.filter(e=>e.attrs?.['data-sma']).length,0,'daily SMA is not drawn as a five-minute SMA');
assert.equal(ids['show-sma'].disabled,true);
chart.onpointermove({clientX:5,clientY:100});
assert.match(ids['hover-tip'].textContent,/20:30.*ไทย/);
assert.match(ids['hover-tip'].textContent,/ไทย/);
assert.doesNotMatch(ids['hover-tip'].textContent,/SMA/);
ids['zoom-in'].onclick();assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,39);
ids['pan-left'].onclick();assert.match(ids['series-caption'].textContent,/5 นาที/);
ids['pan-right'].onclick();
ids['chart-range'].onchange();assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,78);
ids['measure'].onclick();chart.onpointerdown({clientX:5,clientY:100});chart.onpointerdown({clientX:657,clientY:100});
assert.match(ids['measure-output'].textContent,/%/);
assert.equal(ids.measure.attrs['aria-pressed'],'true');
ids['fullscreen'].onclick();assert.equal(ids.fullscreen.attrs['aria-pressed'],'true');
docEvents.keydown({key:'Escape'});assert.equal(ids.fullscreen.attrs['aria-pressed'],'false');
chart.onwheel({shiftKey:true,deltaY:-1,preventDefault(){}});
assert.ok(chart.children.filter(e=>e.attrs?.['data-candle']).length<78);
ids['bar-size'].value='60';ids['bar-size'].onchange();
assert.equal(chart.children.filter(e=>e.attrs?.['data-candle']).length,7,'six full hours plus final half hour');
const raw=demo.stocks[0].intraday.map(b=>({...b,session:b.day,day:b.at}));
const grouped=second.groupIntraday(raw,60);
assert.equal(grouped[0].open,100);assert.equal(grouped[0].high,113);assert.equal(grouped[0].close,112);
assert.equal(second.groupIntraday(raw.slice(1),60)[0].open,null,'missing opening sample must not fabricate OHLC');
ids['chart-range'].value='10y';ids['chart-range'].onchange();
assert.match(ids['candle-note'].textContent,/เกินประวัติ/);
ids['bar-size'].value='day';ids['bar-size'].onchange();assert.equal(ids['show-sma'].disabled,false);
ids['chart-range'].value='1d';ids['chart-range'].onchange();assert.equal(ids['point-slider'].disabled,true,'no daily data for latest intraday day');
ids['reset-view'].onclick();assert.equal(ids['bar-size'].value,'auto');
// Whole-portfolio chart must use aggregate data, not the selected stock series.
demo.portfolio.estimated_cost_total_usd=90.91;
demo.portfolio.live={complete:true,total_usd:120,cost_usd:90.91,gain_usd:29.09,gain_pct:32,day_change_usd:2,day_change_pct:1.7,session_date:'2026-09-23',oldest_quote_as_of:'2026-09-23T15:00:00Z',newest_quote_as_of:'2026-09-23T15:00:00Z',cost_estimated:true,allocations:demo.portfolio.allocations};
Object.assign(demo.portfolio.holdings[0],{live_price:240,live_value_usd:120,live_gain_usd:29.09,live_gain_pct:32,live_weight_pct:100});
demo.portfolio_observations=[{day:'2026-09-23T14:30:00Z',value_usd:118,cost_usd:90.91},{day:'2026-09-23T15:00:00Z',value_usd:120,cost_usd:90.91}];
demo.portfolio_history=[{day:'2020-01-01',value_usd:50},{day:'2026-09-22',value_usd:115}];
demo.portfolio_intraday=[];
demo.benchmark={as_of:'2026-09-22',ranges:{all:[{day:'2026-09-21',value_usd:0,benchmark_pct:0},{day:'2026-09-22',value_usd:2,benchmark_pct:1}]}};
ids['portfolio-data'].textContent=JSON.stringify(demo);
vm.runInNewContext(script,{document,Intl,Date,Map,Number,Math,JSON,String});
assert.equal(ids['portfolio-total'].textContent,'$120.00');
assert.equal(ids['portfolio-gain'].textContent,'+$29.09');
assert.match(ids['portfolio-gain-pct'].textContent,/32\.00%/);
assert.equal(ids['portfolio-chart'].children.filter(e=>e.attrs?.['data-portfolio-line']).length,1);
ids['portfolio-point'].oninput({target:{value:'0'}});
assert.match(ids['portfolio-hover'].textContent,/118\.00/);
ids['portfolio-chart'].onkeydown({key:'End',preventDefault(){}});
assert.match(ids['portfolio-hover'].textContent,/120\.00/);
ids['portfolio-series'].value='simulation';ids['portfolio-series'].onchange();
assert.match(ids['portfolio-history-note'].textContent,/ไม่ใช่ประวัติเงินจริง/);
assert.match(ids['portfolio-hover'].textContent,/115\.00/);
ids['portfolio-range'].value='1d';ids['portfolio-range'].onchange();
assert.equal(ids['portfolio-chart'].onpointermove,null);
assert.equal(ids['portfolio-point'].disabled,true);
ids['portfolio-fullscreen'].onclick();assert.equal(ids['portfolio-fullscreen'].attrs['aria-pressed'],'true');
docEvents.keydown({key:'Escape'});assert.equal(ids['portfolio-fullscreen'].attrs['aria-pressed'],'false');
ids['holdings-sort'].value='gain';ids['holdings-sort'].onchange();
assert.equal(ids['holdings-rows'].children[0].children[5].textContent,'+$29.09');
ids['portfolio-range'].value='all';ids['portfolio-series'].value='benchmark';ids['portfolio-series'].onchange();
assert.equal(ids['portfolio-chart'].children.filter(e=>e.attrs?.['data-benchmark-line']).length,1);
assert.match(ids['portfolio-hover'].textContent,/S&P 500/);
assert.match(ids['portfolio-history-note'].textContent,/ไม่ใช่ผลตอบแทน DCA จริง/);
console.log('Portfolio and stock chart interaction simulations passed: money, history labels, range, hover, keyboard, slider, fullscreen, sorting, intraday and daily charts.');
